version: '3'
services:
 web:
  image: nginx:alpine
  ports:
   - "8080:80"
  volumes:
   - ./site.conf:/etc/nginx/conf.d/default.conf
   - ./index.php:/var/www/html/index.php
 php:
  image: my-php
  volumes:
   - ./index.php:/var/www/html/index.php
 db:
  image: mysql:5.7
  environment:
   MYSQL_ROOT_PASSWORD: mysecretpassword
   MYSQL_DATABASE: test_db
